### ISSUE TITLE
add support for URL query-parameters

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/vembedr#1]
Will need to import httr
- [Vimeo embedding](https://developer.vimeo.com/player/embedding)
- [YouTube embedding](https://developers.google.com/youtube/player_parameters)

**Comment by ginolhac** [comment]
not sure if this is what you meant, but I'd like the url variables to be parsed or set as parameters.
Especially the ability to start at a specific time, such as `4m12s`:
[https://youtu.be/8SGif63VW6E?t=4m12s](https://youtu.be/8SGif63VW6E?t=4m12s)

**Comment by ijlyttle** [comment]
This is exactly what I had in mind, I imagine it will be a matter of providing a list to act as the query parameters, something like:

``` r
rickroll_youtube(param = list(...))
```

**Comment by ginolhac** [comment]
great! I'd love this. Did you check the video, 4m12s out of curiosity? ;)

**Comment by ijlyttle** [comment]
I just did - nice quote!

**Comment by ijlyttle** [comment]
done in ce00aca446030df910b349e4156042bfe803a633

start time can be specified by:

``` R
embed_youtube("8SGif63VW6E", query = list(start = secs("4m12s")))
```

**Comment by ginolhac** [comment]
Perfect! thanks, much appreciated Ian.
