### ISSUE TITLE
can you render to pdf beamer and still play the video?

### ISSUE THREAD

**Issue by Emaasit** [ijlyttle/vembedr#21]

**Comment by ijlyttle** [comment]
I will claim that this works for html - it might not survive the pdf conversion.

I'll leave this open for the question to be answered.

**Comment by Emaasit** [comment]
@ijlyttle Are there any other alternative packages for embedding videos in beamer/pdf files?

**Comment by ijlyttle** [comment]
Not to my knowledge.

**Comment by ijlyttle** [comment]
I don't think this can work, closing.
