### ISSUE TITLE
embed_url and start issue

### ISSUE THREAD

**Issue by pssguy** [ijlyttle/vembedr#23]
embed_url("https://youtu.be/1-vcErOPofQ?t=28s")  starts at 28s

Full url
embed_url("https://www.youtube.com/watch?v=1-vcErOPofQ&feature=youtu.be?t=28s") starts at beginning

**Comment by ijlyttle** [comment]
For this URL:

```
https://www.youtube.com/watch?v=1-vcErOPofQ&feature=youtu.be?t=28s
```

When I put it into the browser it starts at the beginning, as well.

However, this URL works for me in the browser:

```
https://www.youtube.com/watch?v=1-vcErOPofQ&feature=youtu.be&t=28s
```

It also does the right thing using `embed_url()`.

Closing for now - please reopen if we need to.
