### ISSUE TITLE
rounded frame

### ISSUE THREAD

**Issue by ginolhac** [ijlyttle/vembedr#25]
no idea if this is feasible, but could we have an option to have an iframe with rounded corners?

that would fit better ioslides

a relevant link on [StackOverflow](http://stackoverflow.com/questions/5738985/is-it-possible-to-have-css-rounded-corners-on-an-iframe)

**Comment by ijlyttle** [comment]
Although interesting, I think this is outside the scope of what (as least I think) the package does. 

For me, the mission of this package begins and ends at the `<iframe/>`.

I am interested (outside of this package) to see how rounded corners could be implemented - from my poking around, I see there is some difficulty in Chrome.

**Comment by ginolhac** [comment]
Hi,

no worries, I get your point of view.
Actually, you don't need to change anything, @koncina found a `css` solution that works well. Your package is used within his tweaked version of `ioslides`, called [iosp](https://github.com/koncina/iosp)

this code:

~~~
## Art | by Marcus Volz

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">A compilation of some of my gifs created with <a href="https://twitter.com/hashtag/rstats?src=hash">#rstats</a> <a href="https://twitter.com/hashtag/ggplot2?src=hash">#ggplot2</a> <a href="https://twitter.com/hashtag/gganimate?src=hash">#gganimate</a> <a href="https://twitter.com/hashtag/tweenr?src=hash">#tweenr</a> <a href="https://t.co/nCppSOZv4W">https://t.co/nCppSOZv4W</a></p>&mdash; Marcus Volz (@mgvolz) <a href="https://twitter.com/mgvolz/status/849375922297991168">4 avril 2017</a></blockquote>

```{css}
.vembedr {
  border-radius: 50px;
  overflow: hidden;
  border: 2px solid black;
}

.vembedr iframe {
  margin: -5px;
  width: calc(100% + 10px);
}
```

<div class = "vembedr">
```{r, echo = FALSE}
vembedr::embed_youtube("DQiKHlpy70Q")
```
</div>
~~~

gives:
![image](https://cloud.githubusercontent.com/assets/710181/25452880/6bc6940e-2ac7-11e7-94c0-dcbe7d420bae.png)


Of note, it works with both Chrome and Firefox on mac and GNU/Linux

**Comment by ijlyttle** [comment]
That looks excellent!

In that case, with @konica's permission, maybe the thing to do is to put this into a vignette. 

Reopening!

**Comment by koncina** [comment]
I'm fine with that.
The code can even be simplified by displaying the iframe as a block (I also removed the border for the container as it is optional):

~~~
```{css}
.vembedr {
  border-radius: 50px; /* adjust it to your needs */
  overflow: hidden;
}

.vembedr iframe {
  display: block;
  border: none;
}
```

<div class = "vembedr">
```{r, echo = FALSE}
vembedr::embed_youtube("DQiKHlpy70Q")
```
</div>

~~~

**Comment by ginolhac** [comment]
thanks Eric! And sorry for the user konica (~ koncina) who received an unintended message from Ian ;)

**Comment by ijlyttle** [comment]
Thanks Eric, and sorry to you both! I will get on this!

**Comment by ijlyttle** [comment]
FWIW, this seems to work too (including the css from above):

    ```{r, echo = FALSE}
    library("vembedr")
    library("htmltools")

    embed_youtube("DQiKHlpy70Q") %>% div(class = "vembedr")
    ```

**Comment by ijlyttle** [comment]
Just added this stuff to README, thanks!

**Comment by ijlyttle** [comment]
Reconsidering, given that I am looking to create a function called `div_bs_responsive()`.

This could be a function something like:

```r
div_rounded <- function(..., radius = 50)
```

we could use [htmltools::htmlDependencies()](https://www.rdocumentation.org/packages/htmltools/versions/0.3.6/topics/htmlDependencies) to make sure the CSS comes along for the ride...
