### ISSUE TITLE
video not displayed in rstudio' browser

### ISSUE THREAD

**Issue by ginolhac** [ijlyttle/vembedr#4]
thanks for this package Ian!
when trying your example, nothing is displayed when knitting in rstudio.
Once opened in a regular browser, it works as expected.

**Comment by ijlyttle** [comment]
Thanks, but still stuff to do!

This appears to be a design choice made by RStudio not to support iframes using external URL's in their browser: 

https://github.com/rstudio/rstudioapi/issues/2

If RStudio deem it a concern, I defer to them.

**Comment by ginolhac** [comment]
No worries, I am not expecting a fix. Opening in a browser is just fine. But, I think that's a great advantage of github, open an issue so anyone can see your comment about it and knows
